In [ ]:
# Montar disco Drive
from google.colab import drive
drive.mount('/content/drive')


# Importar bibliotecas
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Cargar dataframe
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset/CalidadVino.csv')

df.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [ ]:
# OJO!!! Columna quality --> y



# 1. Eliminar filas nulas
df = df.dropna()

# 2. Eliminar columna type
df.drop('type', axis=1, inplace=True)

In [ ]:
# Con nuestras X
X = df.drop('quality', axis=1)
y = df['quality']

In [ ]:
# Separar los datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Comprobar shape datos
X_train.shape

(5170, 11)

In [ ]:
y_train.shape

(5170,)

In [ ]:
# Normalizar
# Con una función

# A mano
train_mean_x = X_train.mean(axis=0)
train_std_x = X_train.std(axis=0)

In [ ]:
X_train_scaled = (X_train - train_mean_x) / train_std_x

In [ ]:
X_test_scaled = (X_test - train_mean_x) / train_std_x

In [ ]:
# Contruir modelo

model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)

])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
# compile
# optimizer
# loss

model.compile(optimizer='adam', loss='mean_squared_error')

In [ ]:
# ENTRENAMIENTO

history = model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.0032
Epoch 2/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1.2634
Epoch 3/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.7675
Epoch 4/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.6032
Epoch 5/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5259
Epoch 6/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5010
Epoch 7/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4807
Epoch 8/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4794
Epoch 9/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4423
Epoch 10/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4621
Epoch 11/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4462
Epoch 12/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4548
Epoch 13/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4183
Epoch 14/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4229
Epoch 15/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4151
Epoch 16/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4056
Epoch 17/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3924
Epoch 18/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3981
Epoch 19/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3867
Epoch 20/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3951
Epoch 21/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3922
Epoch 22/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3749
Epoch 23/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3642
Epoch 24/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3678
Epoch 25/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3585
Epoch 26/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3653
Epoch 27/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3685
Epoch 28/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3480
Epoch 29/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3616
Epoch 30/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3253
Epoch 31/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3283
Epoch 32/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3475
Epoch 33/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3281
Epoch 34/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3390
Epoch 35/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3355
Epoch 36/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3192
Epoch 37/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3177
Epoch 38/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3123
Epoch 39/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3141
Epoch 40/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2972
Epoch 41/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3047
Epoch 42/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3013
Epoch 43/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2955
Epoch 44/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2792
Epoch 45/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2728
Epoch 46/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2799
Epoch 47/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2876
Epoch 48/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2725
Epoch 49/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2672
Epoch 50/50
162/162 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2705

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │         8,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 52,229 (204.02 KB)

 Trainable params: 17,409 (68.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 34,820 (136.02 KB)

In [ ]:
# Evaluar el modelo

results = model.evaluate(X_test_scaled, y_test)
print('Test loss', results)

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5608
Test loss 0.5126881003379822

In [ ]:
# Predecir los 2 primeros

y_pred = model.predict(X_test_scaled[:2])
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step

array([[5.955296 ],
       [5.8674107]], dtype=float32)

In [ ]:
# Comprobar exactitud predicción
y_test[:2]

1143    5
2708    6
Name: quality, dtype: int64